import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/toaster";
const inter = Inter({ subsets: ["latin"] });
import { EdgeStoreProvider } from "../lib/edgestore";
import dbConnect from "@/lib/db";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

dbConnect();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${inter.className}`}>
          <main>
            <EdgeStoreProvider>{children}</EdgeStoreProvider>
          </main>
          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}
